<?php $this->headScript()->captureStart() ?>

var geocoder;
var map;
var marker;
var lat =  <?php echo $this->lat; ?>;
var lon = <?php echo $this->lon; ?>;
var zoom = <?php echo $this->zoom; ?>;;


 function initialize() {

    if (lat == 0 && lon == 0){
        lat = 48.20833;
        lon = 16.373064;
        }
    if (zoom == 0){
        zoom = 12;
        }

    var myLatlng = new google.maps.LatLng(lat, lon);
    var myOptions = {
      zoom: zoom,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.HYBRID
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    geocoder = new google.maps.Geocoder();
    marker = new google.maps.Marker();

    google.maps.event.addListener(map, 'click', function(event) {
    placeMarker(event.latLng);
  });


  }

  function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address,'region': 'at'}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);

       placeMarker(results[0].geometry.location);

            var infowindow = new google.maps.InfoWindow({content: 'Hier gibts bald keine Gelsen mehr!'});
            infowindow.open(map, marker);


      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  function placeMarker(location) {
  var clickedLocation = new google.maps.LatLng(location);
  marker.setMap(map);
  marker.setPosition(location);
  

   document.getElementById("position").innerHTML="Position clicked " + location.lat()
        + " " + location.lng();

   document.getElementById ("G_LAT").value = location.lat();
   document.getElementById ("G_LON").value = location.lng();

  //map.setCenter(location);
}


 function loadScript() {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://maps.google.com/maps/api/js?sensor=false&callback=initialize";
    document.body.appendChild(script);
  }
  window.onload = loadScript;

<?php $this->headScript()->captureEnd() ?>
  <table>
  <tr>
      <th colspan="2">
  <h1>GEBL-Karte: Punkte eingeben</h1>
      </th>
  </tr>
   <tr>
      <td colspan="3">
          <div>
            <input id="address" type="textbox" size="50" value="2452 Mannersdorf" onchange="codeAddress()">
            <input type="button" value="Setze Marker auf Adresse" onclick="codeAddress()">
           </div>
      </td>
  </tr>
  <tr>
    <td id="map">
        <div id="map_canvas" class="maphalf"></div>
        <div>
        <p id="position"></p>
        </div>
    </td>
    <td>
        <div>
        <?php echo $this->form; ?>
        </div>
        <p><a id="showpoint" href="/admin/showallpoints">Alle Punkte anzeigen</a></p>
    </td>
  </tr>
  </table>