<?php
$this->headScript()->appendFile(
        '/js/gmap.js',
        'text/javascript'
);

$this->headScript()->appendFile(
        '/js/adminshowallpoints.js',
        'text/javascript'
);


$this->headScript()->captureStart()
?>

var geocoder;
var map;
var lat =  <?php if ($this->lat) {
    echo $this->lat;
} else {
    echo "0";
}; ?>;
var lon = <?php if ($this->lat) {
    echo $this->lon;
} else {
    echo "0";
}; ?>;
var zoom = <?php if ($this->zoom) {
    echo $this->zoom;
} else {
    echo "0";
}; ?>;
var markerid = <?php if ($this->id) {
    echo $this->id;
} else {
    echo "0";
}; ?>;

var urlmarkers = "/admin/listallpoints?format=xml"
var placemarkerok = true;
var clickedmarker;
var clickedmarkericon =  "/images/exitanimated.gif";

var customIconsBrut = {
0: {
icon: '/images/waterred.png'
},
1: {
icon: '/images/watergreen.png'
}
};

var customIcons = {
1: {
icon: '/images/villa.png'
},
2: {
icon: '/images/exit.png'
},
3: {
icon: '/images/watergreen.png'
}
};

function showall(){
    window.location.href="/admin/showallpoints"
    + "/lat/" + map.getCenter().lat()
    + "/lon/" +  map.getCenter().lng()
    + "/zoom/" + map.getZoom();
  }

window.onload = loadScript;



<?php $this->headScript()->captureEnd() ?>

 
<div id ="outer">

    <div id ="header">
        <a href="/index/logout">Logout</a>
        <h1>GEBL-Karte: Falle eingeben</h1>
    </div>
    <div id="header2">
	      <p><input id ="showbrut" type="button" value="Alle Punkte anzeigen" onclick="showall()"/></p>
		
          <p>
           <input id="address" type="textbox" size="50" value="2452 Mannersdorf" onchange="codeAddress()">
          <input type="button" value="Zentriere Karte auf Adresse" onclick="codeAddress()"> 
          </p>
          
    </div>
    <div id="centrecontent">
       
        <div id="left">
            <div id="map_canvas" class="maphalf"></div>
            <img src="/images/waterredsmall.png" alt="roter_marker" align="middle"/> ungeprüfte Brutstätte
            <img src="/images/watersmall.png" alt="gruener_marker" align="middle"/> geprüfte Brutstätte
            <img src="/images/villasmall.png" alt="blauer_marker" align="middle"/> Adresse
            <img src="/images/exitsmall.png" alt="brauner_marker" align="middle"/> Falle
        </div>
        <div id="right">
        <?php echo $this->form; ?>
        <input id ="showbrut" type="button" value="Abbrechen" onclick="showall()"/>
        </div>
    </div>
     <div class="clearer"></div>
</div>
<div id="footer">
 Felder mit * sind Pflichtfelder
 </div>  
  
  
  
  
  
  