<?php
$this->headScript()->captureStart()
?>



function showall(){
    window.location.href="/admin/showallpoints"
  }
<?php $this->headScript()->captureEnd() ?>





<div id ="outer">

    <div id ="header">
        <?php   $this->auth = Zend_Auth::getInstance();
                 if ($this->auth->hasIdentity() &&
                        is_object($this->auth->getIdentity())) {
                    echo ("Angemeldet als '".$this->auth->getIdentity()->P_LOGNAME
                            ."'<br> <a href='/index/logout'>Abmelden</a> ");
                }else{
                   echo ("<a href='/index/login'>Anmelden</a>");
                }
         ?>
        <h1>GEBL-Karte: Benutzerverwaltung</h1>
    </div>
    
    <div id="centrecontent">
        <?php echo $this->form; ?>
        <input id ="showbrut" type="button" value="Abbrechen" onclick="showall()"/>
        
    </div>
     <div class="clearer"></div>
</div>
<div id="footer">
 Felder mit * sind Pflichtfelder
 </div>  
  
  
  
  
  
  