<?php
$this->headScript()->appendFile(
        '/js/gmap.js',
        'text/javascript'
);

$this->headScript()->appendFile(
        '/js/guestshowallbrutstaetten.js',
        'text/javascript'
);


$this->headScript()->captureStart()
?>

var geocoder;
var map;
var lat =  <?php if ($this->lat) {
    echo $this->lat;
} else {
    echo "48.01208";
}; ?>;
var lon = <?php if ($this->lat) {
    echo $this->lon;
} else {
    echo "16.722139";
}; ?>;
var zoom = <?php if ($this->zoom) {
    echo $this->zoom;
} else {
    echo "12";
}; ?>;
var markerid = <?php if ($this->id) {
    echo $this->id;
} else {
    echo "0";
}; ?>;

var urlmarkers = "/admin/listallpoints?format=xml"
var placemarkerok = true;
var clickedmarker;
var clickedmarkericon =  "/images/waterred.png";

var customIconsBrut = {
0: {
icon: '/images/waterred.png'
},
1: {
icon: '/images/water.png'
}
};

var customIcons = {
      1: {
        icon: '/images/villa.png'
        },
      2: {
        icon: '/images/exit.png'
        },
      3: {
        icon: '/images/water.png'
        }

    };

function showall(){
    window.location.href="/admin/showallpoints"
    + "/lat/" + map.getCenter().lat()
    + "/lon/" +  map.getCenter().lng()
    + "/zoom/" + map.getZoom();
  }

window.onload = loadScript;






/* old javascript now in external js file!
var geocoder;
var map;
var marker;
var lat =  <?php if ($this->lat) {echo $this->lat;} else {echo "48.20833";}; ?>;
var lon = <?php if ($this->lat) {echo $this->lon;} else {echo "16.373064";}; ?>;
var zoom = <?php if ($this->zoom) {echo $this->zoom;} else {echo "12";}; ?>;

 function initialize() {
   
    var myLatlng = new google.maps.LatLng(lat, lon);
    var myOptions = {
      zoom: zoom,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.HYBRID
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    geocoder = new google.maps.Geocoder();
    marker = new google.maps.Marker();

    google.maps.event.addListener(map, 'click', function(event) {
    placeMarker(event.latLng);
  });


  }

  function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address,'region': 'at'}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);

       placeMarker(results[0].geometry.location);

            var infowindow = new google.maps.InfoWindow({content: 'Bitte Daten zu diesem Punkt eingeben!'});
            infowindow.open(map, marker);


      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  function placeMarker(location) {
  var clickedLocation = new google.maps.LatLng(location);
  marker.setMap(map);
  marker.setPosition(location);
  marker.setIcon('/images/water.png');
  
   document.getElementById ("G_LAT").value = parseFloat(location.lat());
   document.getElementById ("G_LON").value = parseFloat(location.lng());

  //map.setCenter(location);
}


 function loadScript() {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://maps.google.com/maps/api/js?sensor=false&callback=initialize";
    document.body.appendChild(script);
  }

  function showall(){
    window.location.href="/ADMIN/showallpoints"
    + "/lat/" + map.getCenter().lat()
    + "/lon/" +  map.getCenter().lng()
    + "/zoom/" + map.getZoom();
  }

  window.onload = loadScript;
*/


<?php $this->headScript()->captureEnd() ?>
  
  <div id="outer">

    <div id="header">
        <a href="/index/logout">Logout</a>
        <h1>GEBL-Karte: Brutstättendaten editieren</h1>
    </div>
           
    <div id="header2">
          <p><input id ="showbrut" type="button"
          value="Alle gespeicherten Punkte anzeigen" onclick="showall()"/></p>
         <p>
            <p>
            <input id="address" type="textbox" size="50" value="Wilfleinsdorf" onchange="codeAddress()">
            <input type="button" value="Setze Marker auf Adresse" onclick="codeAddress()">
            </p>
    </div>

    <div id="centrecontent">
        <div id ="left">
        <div id="map_canvas" style="height: 500px;width: 379px"></div>
        </div>


        <div id="right">
        <?php echo $this->form; ?>
        </div>
    </div>
  </div>
  <div id="clearer"></div>
  <div id="footer">
  Ändern der Koordinaten: Karte clicken. Daten korrigieren und "Ändern"-Button drücken. Felder mit * sind Pflichtfelder.
  </div>
