<?php

$dom = new DOMDocument("1.0");
$node = $dom->createElement("brutstaetten");
$parnode = $dom->appendChild($node);


header("Content-type: text/xml");

// Iterate through the rows, adding XML nodes for each

//foreach ($this->brutst as $brut) {

  // ADD TO XML DOCUMENT NODE

  $node = $dom->createElement("brutstaette");
  $newnode = $parnode->appendChild($node);
  $parnode = $newnode;
  $newnode->setAttribute("b_id",$this->brutst['B_ID']);
  $newnode->setAttribute("b_nr",$this->brutst['B_NR']);
  $newnode->setAttribute("b_groesse",$this->brutst['B_GROESSE']);
  $newnode->setAttribute("b_gewaesser_art",$this->brutst['B_GEWAESSER_ART']);
  $newnode->setAttribute("b_zugang",$this->brutst['B_ZUGANG']);
  $newnode->setAttribute("b_p_id",$this->brutst['B_P_ID']);
  $newnode->setAttribute("b_g_id",$this->brutst['B_G_ID']);
  $newnode->setAttribute("b_bek_art",$this->brutst['B_BEK_ART']);
  $newnode->setAttribute("b_text",$this->brutst['B_TEXT']);
  $newnode->setAttribute("b_kontaktdaten",$this->brutst['B_KONTAKTDATEN']);
  foreach ($this->akt as $aktion) {
    $node = $dom->createElement("aktion");
    $newnode = $parnode->appendChild($node);
    $newnode->setAttribute("a_id",$aktion['A_ID']);
    $newnode->setAttribute("a_nr",$aktion['A_NR']);
    $newnode->setAttribute("a_typ",$aktion['A_TYP']);
    $newnode->setAttribute("a_betreff",$aktion['A_BETREFF']);
    $newnode->setAttribute("a_datum",$aktion['A_DATUM']);
    $newnode->setAttribute("a_p_id",$aktion['A_P_ID']);
    $newnode->setAttribute("a_b_id",$aktion['A_B_ID']);
    $newnode->setAttribute("a_f_id",$aktion['A_F_ID']);
    $newnode->setAttribute("a_text",$aktion['A_TEXT']);
    
  }

echo $dom->saveXML();

?>