<?php
$this->headScript()->appendFile(
        '/js/gmap.js',
        'text/javascript'
);

$this->headScript()->appendFile(
        '/js/admincudallpoints.js',
        'text/javascript'
);


$this->headScript()->captureStart();
?>

var geocoder;
var map;
var lat =  <?php if ($this->lat) {
    echo $this->lat;
} else {
    echo "48.01208";
}; ?>;
var lon = <?php if ($this->lat) {
    echo $this->lon;
} else {
    echo "16.722139";
}; ?>;
var zoom = <?php if ($this->zoom) {
    echo $this->zoom;
} else {
    echo "12";
}; ?>;
var markerid = "-1"; //No Marker !!!!;

var urlmarkers = "/admin/listallpoints?format=xml";
var placemarkerok = false;
var clickedmarker;
var clickedmarkericon =  "/images/waterred.png";

var customIconsBrut = {
0: {
icon: '/images/waterred.png'
},
1: {
icon: '/images/watergreen.png'
}
};

var customIconsBrutAnimated = {
0: {
icon: '/images/waterredanimated.gif'
},
1: {
icon: '/images/watergreenanimated.gif'
}
};

var customIcons = {
      1: {
        icon: '/images/villa.png'
        },
      2: {
        icon: '/images/exit.png'
        },
      3: {
        icon: '/images/watergreen.png'
        }

    };

function showall(){
    window.location.href="/admin/showallpoints"
    + "/lat/" + map.getCenter().lat()
    + "/lon/" +  map.getCenter().lng()
    + "/zoom/" + map.getZoom();
  }

window.onload = loadScript;






/*
old code moved to js files
-----------------------------------------


var geocoder;
var map;
var lat =  <?php echo $this->lat; ?>;
var lon = <?php echo $this->lon; ?>;
var zoom = <?php echo $this->zoom; ?>;


var customIcons = {
      1: {
        icon: '/images/villa.png'
        },
      2: {
        icon: '/images/exit.png'
        },
      3: {
        icon: '/images/watergreen.png'
        },
      4: {
        icon: '/images/waterred.png'
        }
    };


 function initialize() {

    if (lat == 0 && lon == 0){
    lat = 48.20833;
    lon = 16.373064;
    }
    if (zoom == 0){
    zoom = 12;
    }
    var myLatlng = new google.maps.LatLng(lat, lon);
    var myOptions = {
      zoom: zoom,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.HYBRID
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    geocoder = new google.maps.Geocoder();


    //draw points from xml
     var infoWindow = new google.maps.InfoWindow;
    // Change this depending on the name of your PHP file
      downloadUrl("/admin/listallpoints?format=xml", function(data) {
     var xml = parseXml(data);
     var markers = xml.documentElement.getElementsByTagName("marker");
     for (var i = 0; i < markers.length; i++) {
        var id = markers[i].getAttribute("id");
        var name = markers[i].getAttribute("name");
        var typ = markers[i].getAttribute("typ");
        var checked = markers[i].getAttribute("checked");
        //unchecked Brutstaette is Typ 4
        if (checked == "0" && typ == "3"){typ = "4"};
        var point = new google.maps.LatLng(
              parseFloat(markers[i].getAttribute("lat")),
              parseFloat(markers[i].getAttribute("lon")));
        var icon = customIcons[typ] || {};
        var marker = new google.maps.Marker({
            map: map,
            position: point,
            icon: icon.icon,
            shadow: icon.shadow
            });
          marker.set("name",name);
          marker.set("typ",typ);
          marker.set("id",id);
          marker.set("checked",checked);
          bindInfoWindow(marker, map, infoWindow);
        }
      });
        
  }

   function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address,'region': 'at'}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);

      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  function placeMarker(location) {
  var clickedLocation = new google.maps.LatLng(location);
  var marker = new google.maps.Marker({
      position: location,
      map: map
  });

   document.getElementById("position").innerHTML="Position clicked " + location.lat()
        + " " + location.lng();
  //map.setCenter(location);
}

   function bindInfoWindow(marker, map, infoWindow) {
      google.maps.event.addListener(marker, 'click', function() {
          
          document.getElementById("pointname").innerHTML="Name: " + marker.get("name");
          var html = ""
          var markerid = marker.get('id');
          var markername = marker.get('name');
           //if(document.getElementById("deletepoint")){
             document.getElementById("deletepoint").href="/admin/deletepoint/id/" + marker.get("id")
                                                          + "/lat/" + map.getCenter().lat()
                                                          + "/lon/" +  map.getCenter().lng()
                                                          + "/zoom/" + map.getZoom();
             document.getElementById("deletepoint").innerHTML="Lösche Punkt mit Namen  " + marker.get('name');
          //}
                 switch (marker.get("typ")){

                 case "1":
                 html = "<h4>"+ markername + "</h4>" + "Typ: Adresse <br>";
                 document.getElementById("info").innerHTML="";
                 break;
                 
                 case "2":
                 html = "<h4>"+ markername + "</h4>" + "Typ: Falle <br>";
                 document.getElementById("info").innerHTML="";
                 break;
                 
                 case "3":
                 html = "<h4>"+ markername + "</h4>" + "Typ: Brutstätte <br>";
                 html = html + "<p><input type='button' value='Weitere Daten laden' onclick='getbrutInfo("+ markerid +")'/></p>";
                 html = html + "<p><input type='button' value='Brutstätte editieren' onclick='editBrut("+ markerid +")'/></p>"
                 document.getElementById("info").innerHTML="";
                 break;

                 case "4": //unchecked Brutstaette
                 html = "<h4>"+ markername + "</h4>" + "Typ: ungeprüfte Brutstätte <br>";
                 html = html + "<p><input type='button' value='Weitere Daten laden' onclick='getbrutInfo("+ markerid +")'/></p>";
                 html = html + "<p><input type='button' value='Brutstätte editieren' onclick='editBrut("+ markerid +")'/></p>"
                 html = html + "<p><input type='button' value='Brutstätte geprüft' onclick='setBrutChecked("+ markerid +")'/></p>";
                 document.getElementById("info").innerHTML="";
                 break;

                 default:
                 document.getElementById("info").innerHTML="";
                 document.getElementById("infobutton").style.visibility = "hidden";
                 }
            infoWindow.setContent(html);
            infoWindow.open(map, marker);
            }
            
        );
    }


    function editBrut(g_id) {
        window.location.href="/admin/editbrutstaette"
    + "/g_id/" + g_id
    + "/lat/" + map.getCenter().lat()
    + "/lon/" +  map.getCenter().lng()
     + "/zoom/" + map.getZoom();
    }

    function setBrutChecked(g_id) {
        window.location.href="/admin/setbrutchecked"
    + "/g_id/" + g_id
    + "/lat/" + map.getCenter().lat()
    + "/lon/" +  map.getCenter().lng()
     + "/zoom/" + map.getZoom();
    }

    function getbrutInfo(g_id){
      document.getElementById("info").innerHTML="Lade Daten ....";

      downloadUrl("/admin/listonebrutstaette/format/xml/g_id/" + g_id, function(data){

                      var xml = parseXml(data);
                      var brut = xml.documentElement.getElementsByTagName("brutstaette");
                      var b_id = brut[0].getAttribute("b_id");
                      var b_nr = brut[0].getAttribute("b_nr");
                      var b_groesse = brut[0].getAttribute("b_groesse");
                      var b_gewaesser_art = brut[0].getAttribute("b_gewaesser_art");
                      var b_zugang = brut[0].getAttribute("b_zugang");
                      var b_p_id = brut[0].getAttribute("b_p_id");
                      var b_g_id = brut[0].getAttribute("b_g_id");
                      var b_bek_art = brut[0].getAttribute("b_bek_art");
                      var b_text = brut[0].getAttribute("b_text");
                      var b_kontaktdaten = brut[0].getAttribute("b_kontaktdaten");
                      var aktionen = xml.documentElement.getElementsByTagName("aktion");
                      var infohtml ="<h4>Daten zu dieser Brutstätte:</h4>" +
                                   "b_id = " + b_id + "<br>" +
                                   "b_nr = " + b_nr + "<br>" +
                                   "b_groesse = " + b_groesse + "<br>" +
                                   "b_gewaesser_art = " + b_gewaesser_art + "<br>" +
                                   "b_zugang = " + b_zugang + "<br>" +
                                   "b_p_id = " + b_p_id + "<br>" +
                                   "b_g_id = " + b_g_id + "<br>" +
                                   "b_bek_art = " + b_bek_art + "<br>" +                                   
                                   "b_text = " + b_text + "<br>" +
                                   "b_kontaktdaten = " + b_kontaktdaten + "<br>";

                      var aktionenhtml = ""
                      for (var i = 0; i < aktionen.length; i++) {
                        aktionenhtml = aktionenhtml +
                         "<h4>Aktion " + i + "</h4>" +
                         "a_id =" + aktionen[i].getAttribute("a_id") + "<br>" +
                         "a_nr =" + aktionen[i].getAttribute("a_nr") + "<br>" +
                         "a_typ =" + aktionen[i].getAttribute("a_typ") + "<br>" +
                         "a_betreff =" + aktionen[i].getAttribute("a_betreff") + "<br>" +
                         "a_datum =" + aktionen[i].getAttribute("a_datum") + "<br>" +
                         "a_p_id =" + aktionen[i].getAttribute("a_p_id") + "<br>" +
                         "a_b_id =" + aktionen[i].getAttribute("a_b_id") + "<br>" +
                         "a_f_id =" + aktionen[i].getAttribute("a_f_id") + "<br>" +
                         "a_text =" + aktionen[i].getAttribute("a_text") + "<br>";
                                       
                        
                      }
                      document.getElementById("info").innerHTML = infohtml + aktionenhtml;
                                  
                      });
    }

    function getadresseInfo(g_id){

    }

    function getfalleInfo(g_id){
      
    }

    function addBrutstaette(){
    window.location.href="/admin/addbrutstaette"
                            + "/lat/" + map.getCenter().lat()
                            + "/lon/" +  map.getCenter().lng()
                            + "/zoom/" + map.getZoom();
    }

    function downloadUrl(url, callback) {
      var request = window.ActiveXObject ?
          new ActiveXObject('Microsoft.XMLHTTP') :
          new XMLHttpRequest;

      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          request.onreadystatechange = doNothing;
          callback(request.responseText, request.status);
        }
      };

      request.open('GET', url, true);
      request.send(null);
    }

    function parseXml(str) {
      if (window.ActiveXObject) {
        var doc = new ActiveXObject('Microsoft.XMLDOM');
        doc.loadXML(str);
        return doc;
      } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
      }
    }

    function doNothing() {}



 function loadScript() {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://maps.google.com/maps/api/js?sensor=false&callback=initialize";
    document.body.appendChild(script);
  }



  window.onload = loadScript;
*/
<?php $this->headScript()->captureEnd() ?>
  
  <div id ="outer"> 
      <div id ="header">
        <a href="/index/logout">Logout</a>
        <h1>GEBL-Karte: Punkte anzeigen</h1>
      </div>
          <div id="header2">
          <p>
          <input id ="addbrut" type="button" value="Weitere Brutstätte eingeben" onclick="addBrutstaette()"/>
          </p>
          <p>
          <input id="address" type="textbox" size="50" value="Mannersdorf" onchange="codeAddress()">
          <input type="button" value="Zentriere Karte auf Adresse" onclick="codeAddress()">
          </p>
          </div>
      <div id="centrecontent">
          
	  <div id="left">
            <div id="map_canvas" class="maphalf"></div>
            <img src="/images/waterredsmall.png" alt="roter_marker" align="middle"/> ungeprüfte Brutstätte
            <img src="/images/watersmall.png" alt="gruener_marker" align="middle"/> geprüfte Brutstätte
            <img src="/images/villasmall.png" alt="blauer_marker" align="middle"/> Adresse
            <img src="/images/exitsmall.png" alt="brauner_marker" align="middle"/> Falle
          </div>
	  
	  <div id="right">
	     <h3 id="pointname"></h3>
             <div id="info"></div>
	   
           </div>
      </div>
       <div class="clearer"></div>
   </div>
  <div id="footer">
      Um weitere Informationen und Optionen zu den Punkten zu erhalten bitte auf den Marker Klicken.
  </div>
 