<?php $this->headScript()->captureStart() ?>

var geocoder;
var map;

var customIcons = {
      1: {
        icon: 'http://google-maps-icons.googlecode.com/files/villa.png'
        },
      2: {
        icon: 'http://google-maps-icons.googlecode.com/files/exit.png'
        },
       3: {
        icon: 'http://google-maps-icons.googlecode.com/files/water.png'
        }
    };


 function initialize() {

    var myLatlng = new google.maps.LatLng(48.20833, 16.373064);
    var myOptions = {
      zoom: 12,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.HYBRID
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    geocoder = new google.maps.Geocoder();


    //draw points from xml
     var infoWindow = new google.maps.InfoWindow;
    // Change this depending on the name of your PHP file
      downloadUrl("listallpoints?format=xml", function(data) {
     var xml = parseXml(data);
     var markers = xml.documentElement.getElementsByTagName("marker");
     for (var i = 0; i < markers.length; i++) {
        var id = markers[i].getAttribute("id");
        var name = markers[i].getAttribute("name");
        var typ = markers[i].getAttribute("typ");
        var point = new google.maps.LatLng(
              parseFloat(markers[i].getAttribute("lat")),
              parseFloat(markers[i].getAttribute("lon")));
        var html = "" + name + " ";
        var icon = customIcons[typ] || {};
        var marker = new google.maps.Marker({
            map: map,
            position: point,
            icon: icon.icon,
            shadow: icon.shadow
            });
          marker.set("name",name);
          marker.set("typ",typ);
          marker.set("id",id);
          bindInfoWindow(marker, map, infoWindow, html);
        }
      });
        
  }

   function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address,'region': 'at'}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);

      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  function placeMarker(location) {
  var clickedLocation = new google.maps.LatLng(location);
  var marker = new google.maps.Marker({
      position: location,
      map: map
  });

   document.getElementById("position").innerHTML="Position clicked " + location.lat()
        + " " + location.lng();
  //map.setCenter(location);
}

   function bindInfoWindow(marker, map, infoWindow, html) {
      google.maps.event.addListener(marker, 'click', function() {
          infoWindow.setContent(html);
          infoWindow.open(map, marker);
          document.getElementById("pointname").innerHTML="Name: " + marker.get("name");
          //document.getElementById("pointtyp").innerHTML="Typ: " + marker.get("typ");
          if(document.getElementById("deletepoint")){
             document.getElementById("deletepoint").href="/admin/deletepoint/id/" + marker.get("id");
             document.getElementById("deletepoint").innerHTML="Lösche Punkt mit ID " + marker.get("id");
           }
                 switch (marker.get("typ")){

                 case "1":
                 document.getElementById("info").innerHTML="";
                 document.getElementById("infobutton").value="Weitere Daten zu dieser Adresse anzeigen";
                 document.getElementById("infobutton").onclick= function(){getadresseInfo(marker.get("id"))};
                 document.getElementById("infobutton").style.visibility = "visible";
                 break;
                 
                 case "2":
                 document.getElementById("info").innerHTML="";
                 document.getElementById("infobutton").value="Weitere Daten zu dieser Falle anzeigen";
                 document.getElementById("infobutton").onclick= function(){getfalleInfo(marker.get("id"))};
                 document.getElementById("infobutton").style.visibility = "visible";
                 break;
                 
                 case "3":
                 document.getElementById("info").innerHTML="";
                 document.getElementById("infobutton").value="Weitere Daten zu dieser Brutstätte anzeigen";
                 document.getElementById("infobutton").onclick= function(){getbrutInfo(marker.get("id"))};
                 document.getElementById("infobutton").style.visibility = "visible";
                 break;

                 default:
                 document.getElementById("info").innerHTML="";
                 document.getElementById("infobutton").style.visibility = "hidden";
                 }

            }
        );
    }

    function getbrutInfo(g_id){
      document.getElementById("info").innerHTML="Lade Daten ....";
      downloadUrl("http://gebl/admin/listonebrutstaette/format/xml/g_id/" + g_id, function(data){
                      var xml = parseXml(data);
                      var brut = xml.documentElement.getElementsByTagName("brutstaette");
                      var b_id = brut[0].getAttribute("b_id");
                      var b_nr = brut[0].getAttribute("b_nr");
                      var b_name = brut[0].getAttribute("b_name");
                      var b_groesse = brut[0].getAttribute("b_groesse");
                      var b_gewaesser_art = brut[0].getAttribute("b_gewaesser_art");
                      var b_zugang = brut[0].getAttribute("b_zugang");
                      var b_p_id = brut[0].getAttribute("b_p_id");
                      var b_g_id = brut[0].getAttribute("b_g_id");
                      var b_bek_art = brut[0].getAttribute("b_bek_art");
                      var b_text = brut[0].getAttribute("b_text");
                      document.getElementById("info").innerHTML=
                                   "<h2>Daten zu dieser Brutstätte:</h2>" +
                                   "b_id = " + b_id + "<br>" +
                                   "b_nr = " + b_nr + "<br>" +
                                   "b_name = " + b_name + "<br>" +
                                   "b_groesse = " + b_groesse + "<br>" +
                                   "b_gewaesser_art = " + b_gewaesser_art + "<br>" +
                                   "b_zugang = " + b_zugang + "<br>" +
                                   "b_p_id = " + b_id + "<br>" +
                                   "b_g_id = " + b_g_id + "<br>" +
                                   "b_bek_art = " + b_bek_art + "<br>" +
                                   "b_text = " + b_text + "<br>" ;
                      });
    }

    function getadresseInfo(g_id){

    }

    function getfalleInfo(g_id){
      
    }

    function downloadUrl(url, callback) {
      var request = window.ActiveXObject ?
          new ActiveXObject('Microsoft.XMLHTTP') :
          new XMLHttpRequest;

      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          request.onreadystatechange = doNothing;
          callback(request.responseText, request.status);
        }
      };

      request.open('GET', url, true);
      request.send(null);
    }

    function parseXml(str) {
      if (window.ActiveXObject) {
        var doc = new ActiveXObject('Microsoft.XMLDOM');
        doc.loadXML(str);
        return doc;
      } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
      }
    }

    function doNothing() {}



 function loadScript() {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://maps.google.com/maps/api/js?sensor=false&callback=initialize";
    document.body.appendChild(script);
  }



  window.onload = loadScript;

<?php $this->headScript()->captureEnd() ?>


  
 <table>
  <tr>
  <th colspan="3">
  <h1>GEBL-Karte: Punkte anzeigen</h1>
  </th>
  </tr>

  <tr>
  <td id="map">
  <div>
    Adresse: <input id="address" type="textbox" value="Wilfleinsdorf">
    <input type="button" value="Zentriere Karte auf Adresse" onclick="codeAddress()">
  </div>
      <div id="map_canvas" style="height: 500px;width: 400px"></div>
   <div>
       <p id="position"></p>
   </div>
   </td>
  <td>
       <h2 id="pointname"></h2>
       <p><a id="pointinfo"> </a></p>
       <input id="infobutton" type="button" style="visibility: hidden" />
       <p><a id="deletepoint" ></a></p>
       <p><a id="addpoint" href="/admin/add-point">Noch einen Punkt eingeben</a></p>
   </td>
   <td style="width: 400px">
        <div id="info"></div>
       
   </td>

  </tr>
  </table>