<?php $this->headScript()->captureStart() ?>

var geocoder;
var map;
var lat =  <?php echo $this->lat; ?>;
var lon = <?php echo $this->lon; ?>;


var customIcons = {
      1: {
        icon: '/images/villa.png'
        },
      2: {
        icon: '/images/exit.png'
        },
       3: {
        icon: '/images/water.png'
        }
    };


 function initialize() {

    if (lat == 0 && lon == 0){
    lat = 48.20833;
    lon = 16.373064;
    }
    var myLatlng = new google.maps.LatLng(lat, lon);
    var myOptions = {
      zoom: 12,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.HYBRID
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    geocoder = new google.maps.Geocoder();


    //draw points from xml
     var infoWindow = new google.maps.InfoWindow;
    // Change this depending on the name of your PHP file
      downloadUrl("/admin/listallpoints?format=xml", function(data) {
     var xml = parseXml(data);
     var markers = xml.documentElement.getElementsByTagName("marker");
     for (var i = 0; i < markers.length; i++) {
        var id = markers[i].getAttribute("id");
        var name = markers[i].getAttribute("name");
        var typ = markers[i].getAttribute("typ");
        var point = new google.maps.LatLng(
              parseFloat(markers[i].getAttribute("lat")),
              parseFloat(markers[i].getAttribute("lon")));
        var icon = customIcons[typ] || {};
        var marker = new google.maps.Marker({
            map: map,
            position: point,
            icon: icon.icon,
            shadow: icon.shadow
            });
          marker.set("name",name);
          marker.set("typ",typ);
          marker.set("id",id);
          bindInfoWindow(marker, map, infoWindow);
        }
      });
        
  }

   function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address,'region': 'at'}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);

      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  function placeMarker(location) {
  var clickedLocation = new google.maps.LatLng(location);
  var marker = new google.maps.Marker({
      position: location,
      map: map
  });

   document.getElementById("position").innerHTML="Position clicked " + location.lat()
        + " " + location.lng();
  //map.setCenter(location);
}

   function bindInfoWindow(marker, map, infoWindow) {
      google.maps.event.addListener(marker, 'click', function() {
          
          document.getElementById("pointname").innerHTML="Name: " + marker.get("name");
          var html = ""
          var markerid = marker.get('id');
          var markername = marker.get('name');
           //if(document.getElementById("deletepoint")){
             document.getElementById("deletepoint").href="/admin/deletepoint/id/" + marker.get("id")
                                                          + "/lat/" + map.getCenter().lat()
                                                          + "/lon/" +  map.getCenter().lng();
             document.getElementById("deletepoint").innerHTML="Lösche Punkt mit Namen  " + marker.get('name');
          //}
                 switch (marker.get("typ")){

                 case "1":
                 html = "<h4>"+ markername + "</h4>" + "Typ: Adresse <br>";
                 document.getElementById("info").innerHTML="";
                 break;
                 
                 case "2":
                 html = "<h4>"+ markername + "</h4>" + "Typ: Falle <br>";
                 document.getElementById("info").innerHTML="";
                 break;
                 
                 case "3":
                 html = "<h4>"+ markername + "</h4>" + "Typ: Brutstätte <br>";
                 html = html + "<p><input type='button' value='Weitere Daten laden' onclick='getbrutInfo("+ markerid +")'/></p>";
                 document.getElementById("info").innerHTML="";
                 break;

                 default:
                 document.getElementById("info").innerHTML="";
                 document.getElementById("infobutton").style.visibility = "hidden";
                 }
            infoWindow.setContent(html);
            infoWindow.open(map, marker);
            }
            
        );
    }

    function getbrutInfo(g_id){
      document.getElementById("info").innerHTML="Lade Daten ....";

      downloadUrl("/admin/listonebrutstaette/format/xml/g_id/" + g_id, function(data){

                      var xml = parseXml(data);
                      var brut = xml.documentElement.getElementsByTagName("brutstaette");
                      var b_id = brut[0].getAttribute("b_id");
                      var b_nr = brut[0].getAttribute("b_nr");
                      var b_name = brut[0].getAttribute("b_name");
                      var b_groesse = brut[0].getAttribute("b_groesse");
                      var b_gewaesser_art = brut[0].getAttribute("b_gewaesser_art");
                      var b_zugang = brut[0].getAttribute("b_zugang");
                      var b_p_id = brut[0].getAttribute("b_p_id");
                      var b_g_id = brut[0].getAttribute("b_g_id");
                      var b_bek_art = brut[0].getAttribute("b_bek_art");
                      var b_text = brut[0].getAttribute("b_text");
                      var aktionen = xml.documentElement.getElementsByTagName("aktion");
                      var infohtml ="<h4>Daten zu dieser Brutstätte:</h4>" +
                                   "b_id = " + b_id + "<br>" +
                                   "b_nr = " + b_nr + "<br>" +
                                   "b_name = " + b_name + "<br>" +
                                   "b_groesse = " + b_groesse + "<br>" +
                                   "b_gewaesser_art = " + b_gewaesser_art + "<br>" +
                                   "b_zugang = " + b_zugang + "<br>" +
                                   "b_p_id = " + b_p_id + "<br>" +
                                   "b_g_id = " + b_g_id + "<br>" +
                                   "b_bek_art = " + b_bek_art + "<br>" +
                                   "b_text = " + b_text + "<br>" ;

                      var aktionenhtml = ""
                      for (var i = 0; i < aktionen.length; i++) {
                        aktionenhtml = aktionenhtml +
                                       "<h4>Aktion " + i + "</h4>" +
                                       "a_id =" + aktionen[i].getAttribute("a_id") + "<br>" +
                                       "a_nr =" + aktionen[i].getAttribute("a_nr") + "<br>" +
                                       "a_typ =" + aktionen[i].getAttribute("a_typ") + "<br>" +
                                       "a_betreff =" + aktionen[i].getAttribute("a_betreff") + "<br>" +
                                       "a_datum =" + aktionen[i].getAttribute("a_datum") + "<br>" +
                                       "a_p_id =" + aktionen[i].getAttribute("a_p_id") + "<br>" +
                                       "a_b_id =" + aktionen[i].getAttribute("a_b_id") + "<br>" +
                                       "a_f_id =" + aktionen[i].getAttribute("a_f_id") + "<br>" +
                                       "a_text =" + aktionen[i].getAttribute("a_text") + "<br>"
                                       ;
                                       
                        
                      }
                      document.getElementById("info").innerHTML = infohtml + aktionenhtml;
                                  
                      });
    }

    function getadresseInfo(g_id){

    }

    function getfalleInfo(g_id){
      
    }

    function addBrutstaette(){
    window.location.href="/admin/addbrutstaette"
                            + "/lat/" + map.getCenter().lat()
                            + "/lon/" +  map.getCenter().lng();
    }

    function downloadUrl(url, callback) {
      var request = window.ActiveXObject ?
          new ActiveXObject('Microsoft.XMLHTTP') :
          new XMLHttpRequest;

      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          request.onreadystatechange = doNothing;
          callback(request.responseText, request.status);
        }
      };

      request.open('GET', url, true);
      request.send(null);
    }

    function parseXml(str) {
      if (window.ActiveXObject) {
        var doc = new ActiveXObject('Microsoft.XMLDOM');
        doc.loadXML(str);
        return doc;
      } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
      }
    }

    function doNothing() {}



 function loadScript() {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://maps.google.com/maps/api/js?sensor=false&callback=initialize";
    document.body.appendChild(script);
  }



  window.onload = loadScript;

<?php $this->headScript()->captureEnd() ?>


  
 <table>
  <tr>
  <th colspan="3">
  <h1>GEBL-Karte: Punkte anzeigen</h1>
  </th>
  </tr>

  <tr>
      <td colspan="3">
          <div>
            <input id="address" type="textbox" size="50" value="Wilfleinsdorf" onchange="codeAddress()">
            <input type="button" value="Zentriere Karte auf Adresse" onclick="codeAddress()">
           </div>
      </td>
  </tr>

  <tr>
  <td id="map">
  
      <div id="map_canvas" style="height: 500px;width: 400px"></div>
   <div>
       <p id="position"></p>
   </div>
   </td>
  <td>
       <h3 id="pointname"></h3>
       <p><a id="pointinfo"> </a></p>
       
       <p><a id="deletepoint" ></a></p>
       <input id ="addbrut" type="button" value="Weitere Brutstätte eingeben" onclick="addBrutstaette()"/>
       
       
   
       <div id="info"></div>
       
   </td>

  </tr>
  </table>