CREATE USER gebl
IDENTIFIED BY XXXXXXXX
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT ALTER SESSION TO gebl;
GRANT CREATE ANY CONTEXT TO gebl;
GRANT CREATE CLUSTER TO gebl;
GRANT CREATE DATABASE LINK TO gebl;
GRANT CREATE DIMENSION TO gebl;
GRANT CREATE INDEXTYPE TO gebl;
GRANT CREATE JOB TO gebl;
GRANT CREATE MATERIALIZED VIEW TO gebl;
GRANT CREATE OPERATOR TO gebl;
GRANT CREATE PROCEDURE TO gebl;
GRANT CREATE SEQUENCE TO gebl;
GRANT CREATE SESSION TO gebl;
GRANT CREATE SYNONYM TO gebl;
GRANT CREATE TABLE TO gebl;
GRANT CREATE TRIGGER TO gebl;
GRANT CREATE TYPE TO gebl;
GRANT CREATE VIEW TO gebl;
GRANT UNLIMITED TABLESPACE TO gebl;