<div id ="outer">

    <div id ="header">
        <a href="/index/index">Als Gast anmelden</a>
        <h1>GEBL-Karte: Login</h1>
     </div>

    <div id ="header2">
               <?php printf('<p> %s </p>', implode(' ',$this->message)); ?>
		<?php echo $this->form; ?>
    </div>

    <div id="centrecontent">
		
    </div>

    <div class="clearer"></div>
</div>
<div id="footer">
    Bitte Login Daten eingeben und "Login" drücken!
</div>