<?php
$this->headScript()->appendFile(
        '/js/gmap.js',
        'text/javascript'
);

$this->headScript()->appendFile(
        '/js/guestshowallbrutstaetten.js',
        'text/javascript'
);


$this->headScript()->captureStart()
?>

var geocoder;
var map;
var lat =  <?php if ($this->lat) {
    echo $this->lat;
} else {
    echo "48.01208";
}; ?>;
var lon = <?php if ($this->lon) {
    echo $this->lon;
} else {
    echo "16.722139";
}; ?>;
var zoom = <?php if ($this->zoom) {
    echo $this->zoom;
} else {
    echo "12";
}; ?>;
var markerid = <?php if ($this->id) {
    echo $this->id;
} else {
    echo "0";
}; ?>;
var urlmarkers = "/guest/listallbrutgeodaten?format=xml"
var placemarkerok = true;
var clickedmarker;
var clickedmarkericon =  "/images/waterredanimated.gif";

var customIconsBrut = {
0: {
icon: '/images/waterred.png'
},
1: {
icon: '/images/water.png'
}
};



window.onload = loadScript;

function showallBrutstaetten(){
window.location.href="/guest/showallbrutstaetten"
+ "/lat/" + map.getCenter().lat()
+ "/lon/" +  map.getCenter().lng()
+ "/zoom/" + map.getZoom();
}



<?php $this->headScript()->captureEnd() ?>


<div id ="outer">

    <div id ="header">
        <a href="/index/login">Login</a>
        <h1>GEBL-Karte: Brutstätte melden</h1>
     </div>

     <div id="header2">
         <p><input id ="showbrut" type="button" 
          value="Alle gemeldeten Brutstätten anzeigen" onclick="showallBrutstaetten()"/></p>
         <p>
          <input id="address" type="textbox" size="50" value="Wilfleinsdorf" onchange="codeAddress()">
          <input type="button" value="Setze Marker auf Adresse" onclick="codeAddress()">
         </p>
          </div>
    
    <div id="centrecontent">
        <div id="left">
            <div id="map_canvas" class="maphalf"></div>
            <img src="/images/waterredsmall.png" alt="roter_marker" align="middle"/> ungeprüfte Brutstätte
            <img src="/images/watersmall.png" alt="gruener_marker" align="middle"/> geprüfte Brutstätte
        </div>
        <div id="right">
        <?php echo $this->form; ?>
        <input id ="showbrut" type="button" value="Abbrechen" onclick="showallBrutstaetten()"/>
        
        </div>
    </div>
     <div class="clearer"></div>
</div>
<div id="footer">
 Bitte Koordinaten in der Karte anklicken, Daten eingeben und "Speichern" drücken. Felder mit * sind Pflichtfelder.
 </div>