<?php $this->headScript()->captureStart() ?>

var geocoder;
var map;
var marker;
var lat =  <?php if ($this->lat) {echo $this->lat;} else {echo "48.20833";}; ?>;
var lon = <?php if ($this->lat) {echo $this->lon;} else {echo "16.373064";}; ?>;
var zoom = <?php if ($this->zoom) {echo $this->zoom;} else {echo "12";}; ?>;

 function initialize() {
   
    var myLatlng = new google.maps.LatLng(lat, lon);
    var myOptions = {
      zoom: zoom,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.HYBRID
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    geocoder = new google.maps.Geocoder();
    marker = new google.maps.Marker();

    google.maps.event.addListener(map, 'click', function(event) {
    placeMarker(event.latLng);
  });


  }

  function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address,'region': 'at'}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);

       placeMarker(results[0].geometry.location);

            var infowindow = new google.maps.InfoWindow({content: 'Bitte Daten zu diesem Punkt eingeben!'});
            infowindow.open(map, marker);


      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  function placeMarker(location) {
  var clickedLocation = new google.maps.LatLng(location);
  marker.setMap(map);
  marker.setPosition(location);
  marker.setIcon('/images/waterred.png');
  

   
   document.getElementById ("G_LAT").value = parseFloat(location.lat());
   document.getElementById ("G_LON").value = parseFloat(location.lng());

  //map.setCenter(location);
}


 function loadScript() {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://maps.google.com/maps/api/js?sensor=false&callback=initialize";
    document.body.appendChild(script);
  }

  function showallBrutstaetten(){
    window.location.href="/guest/showallbrutstaetten"
                            + "/lat/" + map.getCenter().lat()
                            + "/lon/" +  map.getCenter().lng()
                            + "/zoom/" + map.getZoom();
    }

  window.onload = loadScript;

<?php $this->headScript()->captureEnd() ?>
  <table>
  <tr>
      <th colspan="2">
  <h1>GEBL-Karte: Brutstätte melden</h1>
      </th>
  </tr>
   <tr>
      <td colspan="3">
          <div>
            <input id="address" type="textbox" size="50" value="Wilfleinsdorf" onchange="codeAddress()">
            <input type="button" value="Setze Marker auf Adresse" onclick="codeAddress()">
           </div>
      </td>
  </tr>
  <tr>
    <td id="map">
        <div id="map_canvas" style="height: 500px;width: 400px"></div>
        <div>
        <p><input id ="showbrut" type="button" value="Alle gemeldeten Brutstätten anzeigen" onclick="showallBrutstaetten()"/></p>
        </div>
    </td>
    <td>
        <div>
        <?php echo $this->form; ?>
        </div>
        
    </td>
  </tr>
  </table>