<?php

$this->headScript()->appendFile(
    '/js/gmap.js',
    'text/javascript'
    );

$this->headScript()->appendFile(
    '/js/guestshowallbrutstaetten.js',
    'text/javascript'
    );

$this->headScript()->captureStart() ?>


var geocoder;
var map;
var lat =  <?php if ($this->lat) {echo $this->lat;} else {echo "48.01208";}; ?>;
var lon = <?php if ($this->lat) {echo $this->lon;} else {echo "16.722139";}; ?>;
var zoom = <?php if ($this->zoom) {echo $this->zoom;} else {echo "12";}; ?>;
var markerid = <?php if ($this->id) {echo $this->id;} else {echo "0";}; ?>;
var urlmarkers = "/guest/listallbrutgeodaten?format=xml";
var placemarkerok = false;
var clickedmarker;
var clickedmarkericon =  "/images/waterred.png";


var customIconsBrut = {
      0: {
        icon: '/images/waterred.png'
        },
      1: {
        icon: '/images/water.png'
        }
    };



  window.onload = loadScript;

 

<?php $this->headScript()->captureEnd() ?>




  <div id ="outer">
  
      <div id ="header">
        <a href="/index/login">Login</a>
        <h1>GEBL-Karte: Gemeldete Brutstätten </h1>
      </div>

          <div id="header2">
          <p>    
          <input id ="addbrut" type="button" value="Weitere Brutstätte melden" onclick="addBrutstaette()"/>
          </p>
          <p>
          <input id="address" type="textbox" size="50" value="Wilfleinsdorf" onchange="codeAddress()">
          <input type="button" value="Zentriere Karte auf Adresse" onclick="codeAddress()">
          </p>
          </div>
  
      <div id="centrecontent">
        <div id="map_canvas" style="height: 500px;width: 760px"></div>
      </div>
                            
       
       <div class="clearer"></div>
   </div>
  <div id="footer">
       Durch Klicken auf die Marker erhalten Sie weitere Informationen.
             
  </div>